http {
  hostname = "0.0.0.0"
  hostname = ${?HTTP_HOSTNAME}
  port = 80
  port = ${?HTTP_PORT}
  pathPrefix = "/"
  pathPrefix = ${?HTTP_PATH_PREFIX}
  bodyLimitSize = "10mb"
  bodyLimitSize = ${?HTTP_BODY_LIMIT_SIZE}
  cors {
    origin {
      pattern = null
      pattern = ${?CORS_ORIGIN_PATTERN}
    }
  }
}

auth {
  client {
    clientId = null
    clientId = ${?CLIENT_ID}
    clientSecret = null
    clientSecret = ${?CLIENT_SECRET}
  }
  introspect {
    url = "http://localhost:3000/oauth/introspect"
    url = ${?INTROSPECT_URL}
    cacheTtlSec = 30
    cacheTtlSec = ${?INTROSPECT_CACHE_TTL_SEC}
    cacheMaxEntries = 10000
    cacheMaxEntries = ${?INTROSPECT_CACHE_MAX_ENTRIES}
    timeoutMs = 5000
    timeoutMs = ${?INTROSPECT_TIMEOUT_MS}
  }
}

upstream {
  baseURL = "http://localhost:3000"
  baseURL = ${?UPSTREAM_BASEURL}
}
